/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-11-03 09:03:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.khachhangbean;
import bean.sachbean;
import bean.loaibean;
import java.util.ArrayList;
import bo.loaibo;
import bo.sachbo;

public final class sach_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1666863561356L));
    _jspx_dependants.put("jar:file:/D:/javanangcaonhom4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JavaNangCaoNhom4/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bo.loaibo");
    _jspx_imports_classes.add("bean.loaibean");
    _jspx_imports_classes.add("bo.sachbo");
    _jspx_imports_classes.add("bean.sachbean");
    _jspx_imports_classes.add("bean.khachhangbean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"sachserverlet\">Trang chủ</a></li>\r\n");
      out.write("      \r\n");
      out.write("      <li><a href=\"giohangcontroler\">Giỏ hàng</a></li>\r\n");
      out.write("      <li><a href=\"xacnhanmuaController\">Thanh toán</a></li>\r\n");
      out.write("      <li><a href=\"#\">Lịch sử mua hàng</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      <li><a href=\"DangKyServerlet\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("      <li>\r\n");
      out.write("      ");
if(session.getAttribute("dn")==null){ 
      out.write("\r\n");
      out.write("      <a href=\"ktdn\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-log-in\"></span>\r\n");
      out.write("       Login\r\n");
      out.write("       </a>\r\n");
      out.write("       ");
}else{
    		khachhangbean khbean = (khachhangbean) session.getAttribute("dn"); 
    	
      out.write("\r\n");
      out.write("       <a href=\"ktdn\">\r\n");
      out.write("	      <span class=\"glyphicon glyphicon-log-out\"></span>\r\n");
      out.write("	       ");
      out.write("\r\n");
      out.write("	       Log out: ");
      out.print(khbean.getTendn());
      out.write("\r\n");
      out.write("	       </a>\r\n");
      out.write("	       ");
} 
      out.write("\r\n");
      out.write("       </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" class=\"table\">\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td width=\"200\" align=\"top\" > Loai sach\r\n");
      out.write("      <table >\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
loaibo lbo=new loaibo();
      	sachbo sbo=new sachbo();
      	
      out.write("\r\n");
      out.write("       </table>\r\n");
      out.write("    </td>\r\n");
      out.write("      <td width=\"600\" valign=\"top\"> Hien thi sach \r\n");
      out.write("     	<table class=\"table\">\r\n");
      out.write("     	");
      out.write(" \r\n");
      out.write("      ");

      ArrayList<sachbean> dssach = (ArrayList<sachbean>) request.getAttribute("dssach");
    	if(dssach != null){
         	int n=dssach.size();
        	for(int i=0;i<n;i++){
        	sachbean s=dssach.get(i);  
       
      out.write("\r\n");
      out.write("          <tr >\r\n");
      out.write("         <td >\r\n");
      out.write("            <img src=\"");
      out.print(s.getAnh() );
      out.write("\"> <br>\r\n");
      out.write("            ");
      out.print(s.getTensach() );
      out.write(" <br>\r\n");
      out.write("            ");
      out.print(s.getTacgia() );
      out.write(" <br>\r\n");
      out.write("            ");
      out.print(s.getGia() );
      out.write(" <br>\r\n");
      out.write("            <a href=\"htgioControler?ms=");
      out.print(s.getMasach());
      out.write("&ts=");
      out.print(s.getTensach());
      out.write("&gia=");
      out.print(s.getGia());
      out.write("\">\r\n");
      out.write("               <img src=\"buynow.jpg\">\r\n");
      out.write("            </a>\r\n");
      out.write("         </td>\r\n");
      out.write("         ");
i++;
         if(i<n){
         s=dssach.get(i);
      out.write("\r\n");
      out.write("         <td>\r\n");
      out.write("            <img src=\"");
      out.print(s.getAnh() );
      out.write("\"> <br>\r\n");
      out.write("            ");
      out.print(s.getTensach() );
      out.write(" <br>\r\n");
      out.write("            ");
      out.print(s.getTacgia() );
      out.write(" <br>\r\n");
      out.write("            ");
      out.print(s.getGia() );
      out.write(" <br>\r\n");
      out.write("            <a href=\"htgioControler?ms=");
      out.print(s.getMasach());
      out.write("&ts=");
      out.print(s.getTensach());
      out.write("&gia=");
      out.print(s.getGia());
      out.write("\">\r\n");
      out.write("               <img src=\"buynow.jpg\">\r\n");
      out.write("            </a>\r\n");
      out.write("         </td> \r\n");
      out.write("          ");

          	}
         	} 
         	
      out.write("\r\n");
      out.write("         </tr>\r\n");
      out.write("       ");
} 
      out.write(" \r\n");
      out.write("       </table>\r\n");
      out.write("\r\n");
      out.write("      	</td>\r\n");
      out.write("      <td width=\"200\" valign=\"top\"> Tim Kiem \r\n");
      out.write("      	<form action=\"sachserverlet\" method=\"post\" class=\"form-inline\" style=\"display: flex\">\r\n");
      out.write(" 		 <input  name=\"txttk\" type=\"text\" value=\"\" placeholder=\"Nhap tt\" class=\"form-control\"> <br>\r\n");
      out.write("  		 <input name=\"butt\" type=\"submit\" value=\"Search\" class=\"btn btn-primary\">\r\n");
      out.write("		</form>\r\n");
      out.write("      	\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /sach.jsp(60,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("l");
      // /sach.jsp(60,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/sach.jsp(60,6) '${dsloai}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dsloai}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      	<tr class=\"list-group\">\r\n");
            out.write("      		<td class=\"list-group-item\">\r\n");
            out.write("      			<a href=\"sachserverlet?ml=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.getMaloai()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("	              ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l.getTenloai()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("	             </a>\r\n");
            out.write("      		</td>\r\n");
            out.write("      	</tr>\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
